let week=null,quiz=[],idx=0,score=0,streak=0,bestStreak=0,missed=[],answered=false,practiceIndex=0,bonusIndex=0,bonusScore=0;
const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll(".screen")];
function show(id){screens.forEach(s=>s.classList.toggle("hidden",s.id!==id));$("homeBtn").classList.toggle("hidden",id==="home");scrollTo(0,0)}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function speak(t){if(!("speechSynthesis" in window))return alert("Speech is unavailable in this browser.");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.74;speechSynthesis.speak(u)}
function key(){return "sophia-spelling-"+week.week}
function getStats(){return JSON.parse(localStorage.getItem(key())||'{"attempts":[],"missed":{}}')}
function saveStats(pct){const s=getStats();s.attempts.unshift({date:new Date().toLocaleDateString(),score,total:quiz.length,bonus:bonusScore,bonusTotal:(week.bonus||[]).length,pct,bestStreak});s.attempts=s.attempts.slice(0,20);missed.forEach(w=>s.missed[w.word]=(s.missed[w.word]||0)+1);localStorage.setItem(key(),JSON.stringify(s));refreshHome()}
function refreshHome(){const s=getStats(),attempts=s.attempts||[];$("homeAttempts").textContent=attempts.length;$("homeBest").textContent=attempts.length?Math.max(...attempts.map(a=>a.pct))+"%":"0";$("homeStreak").textContent=attempts.length?Math.max(...attempts.map(a=>a.bestStreak||0)):0}
function startPractice(list=week.words){quiz=list;practiceIndex=0;show("practice");renderPractice()}
function renderPractice(){const w=quiz[practiceIndex];$("practiceCount").textContent=(practiceIndex+1)+" of "+quiz.length;$("practiceWord").textContent=w.word}
function startTest(list=week.words){quiz=shuffle(list);idx=0;score=0;streak=0;bestStreak=0;missed=[];bonusIndex=0;bonusScore=0;show("test");renderWord()}
function renderWord(){if(idx>=quiz.length)return (week.bonus||[]).length?startBonus():finish();answered=false;$("answer").value="";$("answer").disabled=false;$("feedback").className="";$("feedback").innerHTML="";$("checkBtn").textContent="Check Answer";$("wordNum").textContent="Word "+(idx+1)+" of "+quiz.length;$("score").textContent=score;$("streak").textContent=streak;$("left").textContent=quiz.length-idx}
function check(){if(answered){idx++;renderWord();return}const typed=$("answer").value.trim().toLowerCase();if(!typed)return;const w=quiz[idx];answered=true;$("answer").disabled=true;if(typed===w.word){score++;streak++;bestStreak=Math.max(bestStreak,streak);$("feedback").className="feedback good";$("feedback").textContent="✅ Correct! Great job!"}else{missed.push(w);streak=0;$("feedback").className="feedback bad";$("feedback").innerHTML="❌ Correct spelling: <b>"+w.word+"</b>";speak(w.word)}$("score").textContent=score;$("streak").textContent=streak;$("checkBtn").textContent=idx===quiz.length-1?((week.bonus||[]).length?"Bonus Round ⭐":"See Results 🏆"):"Next Word ➜"}
function startBonus(){show("bonus");bonusIndex=0;renderBonus()}
function renderBonus(){if(bonusIndex>=(week.bonus||[]).length)return finish();const b=week.bonus[bonusIndex];$("bonusNum").textContent="Bonus "+(bonusIndex+1)+" of "+week.bonus.length;$("bonusQ").textContent=b.sentence;$("bonusFeedback").className="";$("bonusFeedback").innerHTML="";$("bonusChoices").innerHTML=b.choices.map(c=>'<button class="soft bonusChoice" data-v="'+c.replace(/"/g,"&quot;")+'">'+c+"</button>").join("");document.querySelectorAll(".bonusChoice").forEach(btn=>btn.onclick=()=>chooseBonus(btn.dataset.v))}
function chooseBonus(v){const b=week.bonus[bonusIndex];if(v===b.answer){bonusScore++;$("bonusFeedback").className="feedback good";$("bonusFeedback").textContent="✅ Correct!"}else{$("bonusFeedback").className="feedback bad";$("bonusFeedback").innerHTML="❌ Correct answer: <b>"+b.answer+"</b>"}setTimeout(()=>{bonusIndex++;renderBonus()},650)}
function finish(){const total=quiz.length+(week.bonus||[]).length,correct=score+bonusScore,pct=Math.round(correct/total*100);show("results");$("percent").textContent=pct+"%";$("resultTitle").textContent=pct===100?"Perfect Score! 🏆🌟":pct>=90?"Amazing Job! 🌟":pct>=80?"Great Work! 🎉":"Nice Practice! 💪";$("resultText").innerHTML=score+" / "+quiz.length+" spelling correct"+((week.bonus||[]).length?" • "+bonusScore+" / "+week.bonus.length+" bonus correct":"")+" • Best streak: "+bestStreak;$("missedList").innerHTML=missed.length?"<h3>Words to Practice:</h3><div class='wordList'>"+missed.map(w=>"<div class='wordChip'>"+w.word+"</div>").join("")+"</div>":"<p>✨ No spelling words missed! ✨</p>";saveStats(pct)}
function renderMissed(){const s=getStats(),entries=Object.entries(s.missed||{}).sort((a,b)=>b[1]-a[1]);$("savedMissed").innerHTML=entries.length?"<div class='wordList'>"+entries.map(([w,n])=>"<div class='wordChip'>"+w+" <small>("+n+")</small></div>").join("")+"</div>":"<p>No missed words saved yet.</p>";$("missedPracticeBtn").classList.toggle("hidden",!entries.length);$("missedPracticeBtn").onclick=()=>{const list=entries.map(([w])=>week.words.find(x=>x.word===w)).filter(Boolean);if(list.length)startPractice(list)}}
function renderHistory(){const a=getStats().attempts||[];$("historyList").innerHTML=a.length?a.map(x=>"<div class='historyItem'><b>"+x.date+"</b> — "+x.pct+"% ("+x.score+"/"+x.total+" spelling)</div>").join(""):"<p>No test attempts yet.</p>"}
fetch("data/current-week.json?"+Date.now()).then(r=>r.json()).then(data=>{week=data;$("weekTitle").textContent=week.title;refreshHome()}).catch(()=>{$("weekTitle").textContent="Could not load this week's words."});
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{const g=b.dataset.go;if(g==="practice")startPractice();else if(g==="test")startTest();else if(g==="missed"){renderMissed();show("missed")}else if(g==="history"){renderHistory();show("history")}});
$("homeBtn").onclick=()=>show("home");$("practiceHear").onclick=()=>speak(quiz[practiceIndex].word);$("practiceSentence").onclick=()=>speak(quiz[practiceIndex].word+". "+quiz[practiceIndex].sentence+" The word is "+quiz[practiceIndex].word+".");$("practicePrev").onclick=()=>{practiceIndex=(practiceIndex-1+quiz.length)%quiz.length;renderPractice()};$("practiceNext").onclick=()=>{practiceIndex=(practiceIndex+1)%quiz.length;renderPractice()};
$("hearBtn").onclick=()=>speak(quiz[idx].word);$("sentenceBtn").onclick=()=>speak(quiz[idx].word+". "+quiz[idx].sentence+" The word is "+quiz[idx].word+".");$("checkBtn").onclick=check;$("answer").addEventListener("keydown",e=>{if(e.key==="Enter")check()});$("retryBtn").onclick=()=>missed.length?startTest(missed):show("home");$("doneBtn").onclick=()=>show("home");